version: '3.7'

services:
  postgres:
    container_name: postgres
    image: db
    build:
      context: .
    networks:
      - postgres
    # restart: always
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_DATABASE}
      PG_DATA: /usr/local/var/postgresql@14
    env_file:
      - .env
    volumes:
      - pgdata:/usr/local/var/postgresql@14
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:8000
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - postgres
    depends_on:
      # - redis
      - postgres
  # redis:
  #   container_name: redis
  #   image: redis:5
  #   networks:
  #     - webnet
networks:
  postgres:
volumes:
  pgdata: